#!/bin/bash
# Script to help install Python 3.13 on macOS

echo "=== Python 3.13 Installation Guide ==="
echo ""
echo "Current Python version:"
python3 --version
echo ""
echo "=== Method 1: Download from python.org (Recommended) ==="
echo "1. Visit: https://www.python.org/downloads/release/python-3130/"
echo "2. Download: macOS 64-bit universal2 installer"
echo "3. Run the installer"
echo "4. Python 3.13 will be installed alongside Python 3.14"
echo ""
echo "After installation, you can use Python 3.13 with:"
echo "  /Library/Frameworks/Python.framework/Versions/3.13/bin/python3"
echo ""
echo "Or create an alias:"
echo "  alias python3.13='/Library/Frameworks/Python.framework/Versions/3.13/bin/python3'"
echo ""
echo "=== Method 2: Install Homebrew first, then Python 3.13 ==="
echo "1. Install Homebrew:"
echo "   /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
echo ""
echo "2. Install Python 3.13:"
echo "   brew install python@3.13"
echo ""
echo "=== Method 3: Use pyenv (Best for managing multiple versions) ==="
echo "1. Install Homebrew (see Method 2)"
echo "2. Install pyenv:"
echo "   brew install pyenv"
echo ""
echo "3. Add to ~/.zshrc:"
echo "   echo 'export PYENV_ROOT=\"\$HOME/.pyenv\"' >> ~/.zshrc"
echo "   echo 'export PATH=\"\$PYENV_ROOT/bin:\$PATH\"' >> ~/.zshrc"
echo "   echo 'eval \"\$(pyenv init -)\"' >> ~/.zshrc"
echo "   source ~/.zshrc"
echo ""
echo "4. Install Python 3.13:"
echo "   pyenv install 3.13.0"
echo "   pyenv global 3.13.0"
echo ""

